name: Pruebas Unitarias - Feature Extraction
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Descargando codigo
        uses: actions/checkout@v4
      - name: Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Mostrar archivos py encontrados
        run: find . -name "*.py" | sort
      - name: Ejecutar pruebas
        run: |
          TESTFILE=$(find . -name "test_*.py" | head -1)
          echo "Archivo encontrado: $TESTFILE"
          python -m pytest "$TESTFILE" -v
