name: Pruebas Unitarias - Feature Extraction
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Descargando codigo
        uses: actions/checkout@v3
      - name: Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar Pruebas
        run: python -m pytest ./tests/test_feature_extraction.py -v
